 services:
  weather-app:
    build: .
    image: weather-app:latest
    container_name: weather-app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - WEATHER_API_URL=https://api.open-meteo.com/v1/forecast
    volumes:
      - .:/app
    working_dir: /app