replicaCount: 2

image:
  repository: weather-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
   limits:
     cpu: 500m
     memory: 512Mi
   requests:
     cpu: 250m
     memory: 256Mi

env:
  - name: APP_ENV
    value: "local"
  - name: CONFIG_FILE
    value: "/config/local.yaml"

nodeSelector: {}
tolerations: []
affinity: {}
