name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env files
        run: |
          echo "WEATHER_API_URL=https://api.open-meteo.com/v1/forecast" > .env
          echo "PORT=8080" >> .env
          echo "WEATHER_API_URL=https://api.open-meteo.com/v1/forecast" > .test.env
          echo "PORT=8080" >> .test.env

      # Step 3: Build Docker images
      - name: Build Docker images
        run: docker-compose build

      # Step 4: Start containers in detached mode
      - name: Start Docker containers
        run: docker-compose up -d

      # Step 5: Run tests inside the container
      # Replace `weather-app` with your service name in docker-compose
      - name: Run tests
        run: docker exec -t weather-app npm test

      # Step 6: Clean up Docker environment
      - name: Clean up
        if: success() || failure()
        run: docker-compose down --rmi all -v --remove-orphans
